/*
 * generated by Xtext 2.28.0
 */
package gameoflife.ide

import com.google.inject.Guice
import gameoflife.GridDSLRuntimeModule
import gameoflife.GridDSLStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class GridDSLIdeSetup extends GridDSLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new GridDSLRuntimeModule, new GridDSLIdeModule))
	}
	
}
