/*
 * generated by Xtext 2.28.0
 */
package gameoflife


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class GridDSLRuntimeModule extends AbstractGridDSLRuntimeModule {
}
