grammar gameoflife.GridDSL with org.eclipse.xtext.common.Terminals

generate gridDSL "http://www.gameoflife/GridDSL"


Grid: 'Grid:' name = ID
	  'length:' length = INT
	  'width:' width = INT
	  ('percentage' percentage = INT)?
		(cells += Cell)*
;
Cell: 'row:' row = INT
	  'col:' col = INT
	  'state:' state = State
;
enum State:
	DEAD = 'dead' | 
	ALIVE = 'alive'
;

enum Operator:
	LT = '<' |
	EQ = '=' |
	GT = '>'
;